// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFA.Infrastructure;

#nullable disable

namespace SFA.Infrastructure.Migrations
{
    [DbContext(typeof(SfaDbContext))]
    [Migration("20250918002913_AddAgendamento")]
    partial class AddAgendamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SFA.Domain.Entities.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<int>("CriadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTimeOffset>("FimUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fim_utc");

                    b.Property<DateTimeOffset>("InicioUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("inicio_utc");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<int>("ProfissionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profissional_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("agendado")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_agendamento");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_agendamento_paciente_id");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("ix_agendamento_profissional_id");

                    b.HasIndex("CodEmpresa", "PacienteId", "InicioUtc")
                        .HasDatabaseName("ix_agendamento_cod_empresa_paciente_id_inicio_utc");

                    b.HasIndex("CodEmpresa", "ProfissionalId", "InicioUtc")
                        .HasDatabaseName("ix_agendamento_cod_empresa_profissional_id_inicio_utc");

                    b.ToTable("agendamento", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_empresa");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_empresa_nome");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_paciente");

                    b.HasIndex("CodEmpresa", "Documento")
                        .HasDatabaseName("ix_paciente_cod_empresa_documento");

                    b.HasIndex("CodEmpresa", "Nome")
                        .HasDatabaseName("ix_paciente_cod_empresa_nome");

                    b.ToTable("paciente", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfil");

                    b.HasIndex("CodEmpresa", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_perfil_cod_empresa_nome");

                    b.ToTable("perfil", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("CodEmpresa", "Login")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_cod_empresa_login");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_id");

                    b.HasKey("UsuarioId", "PerfilId")
                        .HasName("pk_usuario_perfil");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuario_perfil_perfil_id");

                    b.ToTable("usuario_perfil", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("SFA.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamento_pacientes_paciente_id");

                    b.HasOne("SFA.Domain.Entities.Usuario", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamento_usuarios_profissional_id");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SFA.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("SFA.Domain.Entities.Perfil", "Perfil")
                        .WithMany("UsuariosPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_perfil_perfil_perfil_id");

                    b.HasOne("SFA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosPerfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_perfil_usuario_usuario_id");

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SFA.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("UsuariosPerfis");
                });

            modelBuilder.Entity("SFA.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuariosPerfis");
                });
#pragma warning restore 612, 618
        }
    }
}
