// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFA.Infrastructure;

#nullable disable

namespace SFA.Infrastructure.Migrations
{
    [DbContext(typeof(SfaDbContext))]
    [Migration("20260316222528_SecurePasswordResetTokenHash")]
    partial class SecurePasswordResetTokenHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SFA.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<Guid?>("AlteradoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeletedReason")
                        .HasColumnType("text")
                        .HasColumnName("deleted_reason");

                    b.Property<DateTimeOffset>("FimUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fim_utc");

                    b.Property<DateTimeOffset>("InicioUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("inicio_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("agendado")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_agendamento");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_agendamento_paciente_id");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("ix_agendamento_profissional_id");

                    b.HasIndex("CodEmpresa", "PacienteId", "InicioUtc")
                        .HasDatabaseName("ix_agendamento_cod_empresa_paciente_id_inicio_utc");

                    b.HasIndex("CodEmpresa", "ProfissionalId", "InicioUtc")
                        .HasDatabaseName("ix_agendamento_cod_empresa_profissional_id_inicio_utc");

                    b.ToTable("agendamento", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamento_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<Guid?>("AlteradoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeletedReason")
                        .HasColumnType("text")
                        .HasColumnName("deleted_reason");

                    b.Property<DateTimeOffset?>("FinalizadoUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finalizado_utc");

                    b.Property<DateTimeOffset>("InicioUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("inicio_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_atendimento");

                    b.HasIndex("AgendamentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_atendimento_agendamento_id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_atendimento_paciente_id");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("ix_atendimento_profissional_id");

                    b.HasIndex("CodEmpresa", "AgendamentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_atendimento_cod_empresa_agendamento_id")
                        .HasFilter("\"agendamento_id\" IS NOT NULL");

                    b.HasIndex("CodEmpresa", "PacienteId", "InicioUtc")
                        .HasDatabaseName("ix_atendimento_cod_empresa_paciente_id_inicio_utc");

                    b.HasIndex("CodEmpresa", "ProfissionalId", "InicioUtc")
                        .HasDatabaseName("ix_atendimento_cod_empresa_profissional_id_inicio_utc");

                    b.ToTable("atendimento", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.ConfirmacaoAgendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamento_id");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("RespondidoEmUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("respondido_em_utc");

                    b.Property<string>("RespondidoIp")
                        .HasColumnType("text")
                        .HasColumnName("respondido_ip");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_confirmacao_agendamento");

                    b.HasIndex("AgendamentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_confirmacao_agendamento_agendamento_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_confirmacao_agendamento_token");

                    b.HasIndex("CodEmpresa", "Status", "ExpiresAtUtc")
                        .HasDatabaseName("ix_confirmacao_agendamento_cod_empresa_status_expires_at_utc");

                    b.ToTable("confirmacao_agendamento", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("CodEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodEmpresa"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("CelularWhatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular_whatsapp");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnae")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnae");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("InscricaoEstadualRg")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("inscricao_estadual_rg");

                    b.Property<int>("NumeroImovel")
                        .HasColumnType("integer")
                        .HasColumnName("numero_imovel");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("pais");

                    b.Property<string>("PathLogotipo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path_logotipo");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("RedesSociais")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("redes_sociais");

                    b.Property<string>("ResponsavelClinica")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsavel_clinica");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<bool>("UtilizarCelularParaEnvioMensagens")
                        .HasColumnType("boolean")
                        .HasColumnName("utilizar_celular_para_envio_mensagens");

                    b.HasKey("CodEmpresa")
                        .HasName("pk_empresa");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_empresa_documento");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_empresa_email");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_empresa_id");

                    b.HasIndex("RazaoSocial")
                        .HasDatabaseName("ix_empresa_razao_social");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeletedReason")
                        .HasColumnType("text")
                        .HasColumnName("deleted_reason");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_paciente");

                    b.HasIndex("CodEmpresa", "Documento")
                        .HasDatabaseName("ix_paciente_cod_empresa_documento");

                    b.HasIndex("CodEmpresa", "Nome")
                        .HasDatabaseName("ix_paciente_cod_empresa_nome");

                    b.ToTable("paciente", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_token_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_password_reset_token_usuario_id");

                    b.ToTable("password_reset_token", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfil");

                    b.HasIndex("CodEmpresa", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_perfil_cod_empresa_nome");

                    b.ToTable("perfil", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CelularWhatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular_whatsapp");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("cod_empresa");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("CodEmpresa", "Email")
                        .HasDatabaseName("ix_usuario_cod_empresa_email");

                    b.HasIndex("CodEmpresa", "Login")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_cod_empresa_login");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("PerfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("UsuarioId", "PerfilId")
                        .HasName("pk_usuario_perfil");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuario_perfil_perfil_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_usuario_perfil_usuario_id");

                    b.ToTable("usuario_perfil", (string)null);
                });

            modelBuilder.Entity("SFA.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("SFA.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamento_pacientes_paciente_id");

                    b.HasOne("SFA.Domain.Entities.Usuario", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamento_usuarios_profissional_id");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SFA.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("SFA.Domain.Entities.Agendamento", "Agendamento")
                        .WithOne()
                        .HasForeignKey("SFA.Domain.Entities.Atendimento", "AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_atendimento_agendamento_agendamento_id");

                    b.HasOne("SFA.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atendimento_pacientes_paciente_id");

                    b.HasOne("SFA.Domain.Entities.Usuario", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atendimento_usuarios_profissional_id");

                    b.Navigation("Agendamento");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SFA.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SFA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_token_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SFA.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("SFA.Domain.Entities.Perfil", "Perfil")
                        .WithMany("UsuariosPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_perfil_perfil_perfil_id");

                    b.HasOne("SFA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosPerfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_perfil_usuario_usuario_id");

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SFA.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("UsuariosPerfis");
                });

            modelBuilder.Entity("SFA.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UsuariosPerfis");
                });
#pragma warning restore 612, 618
        }
    }
}
